### ISSUE TITLE
file arguments give runtime error

### ISSUE THREAD

**Issue by DrYSG** [ELLIOTTCABLE/bs-cmdliner#4]
The following code works fine on my Win10 box, OCAML 4.09, dune 2.1.2 but the same code compiled with the latest bucklescript gives a run time error: (yes, the file specified by --path is the same in both cases).

```
D:\CRIME\ocommander>node src\ocommander.bs.js TemplateCreate --name test1 --path package.json

C:\Users\ysg4206\AppData\Roaming\npm\node_modules\bs-platform\lib\js\printexc.js:273
  if (slot.tag) {
       ^
TypeError: Cannot read property 'tag' of undefined
    at format_backtrace_slot (C:\Users\ysg4206\AppData\Roaming\npm\node_modules\bs-platform\lib\js\printexc.js:273:12)
    at Object.raw_backtrace_to_string (C:\Users\ysg4206\AppData\Roaming\npm\node_modules\bs-platform\lib\js\printexc.js:378:19)
    at Object.pp_backtrace (D:\CRIME\ocommander\node_modules\@elliottcable\bs-cmdliner\src\cmdliner_msg.bs.js:461:23)
    at do_result (D:\CRIME\ocommander\node_modules\@elliottcable\bs-cmdliner\src\cmdliner.bs.js:309:24)
    at Object.eval_choice (D:\CRIME\ocommander\node_modules\@elliottcable\bs-cmdliner\src\cmdliner.bs.js:452:12)
    at Object.<anonymous> (D:\CRIME\ocommander\src\ocommander.bs.js:363:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

Here is the source:

```
(* Demo, just print the args. *)
open Cmdliner 
[%%raw "process.argv.shift()"]

let actionHelp = [
 `S "COMMAND HELP";
 `P "Use `$(mname) $(i,COMMAND) --help' for help on a single command.";
 `S Manpage.s_bugs; `P "Email bug reports to jpaasch@draper.com";]

(* Actions *) 

let oCommander () = 
  Printf.printf "* dummy - do not call * "

let templateCreate name path = 
  Printf.printf "TemplateCreate - name: %s path: %s" name path

let templateDetails name = 
  Printf.printf "TemplateDetails - name: %s" name

let templateList () = 
  Printf.printf "TemplateList - " 

let deployStack deployment template provider = 
  Printf.printf "DeployStack - deployment: %s template: %s provider: %s" deployment template provider

let deployRemove deployment template provider = 
  Printf.printf "DeployRemove - deployment: %s template: %s provider: %s" deployment template provider

(* Arguments *)

let nameArg =
  let doc = "$(docv) of the template" in
  Arg.(required & opt (some string) None & info ["n"; "name"] ~docv:"NAME" ~doc)

let pathArg =
  let doc = "$(docv) to template file" in
  Arg.(required & opt (some Arg.non_dir_file) None & info ["p"; "path"] ~docv:"PATH" ~doc)

let deployArg =
  let doc = "$(docv) - name to use for deployment" in
  Arg.(required & opt (some string) None & info ["d"; "deployment"] ~docv:"DEPLOYMENT" ~doc)

let templateArg =
  let doc = "$(docv) - name of template" in 
  Arg.(required & opt (some string) None & info ["t"; "template"] ~docv:"TEMPLATE" ~doc)

let providerArg = 
  let doc = "$(docv) - cloud Provider (e.g. AWS)" in
  Arg.(required & opt (some string) None & info ["p"; "provider"] ~docv:"PROVIDER" ~doc)

(* Help Terms *)

let oCommanderHelp =
  let doc = "CLI for CRIME System" in
  let exits = Term.default_exits in
  let man =  [`Blocks actionHelp; ] in
  Term.(const oCommander $ const ()),
  Term.info "oCommander" ~doc ~exits ~version:"0.1.0" ~man

let templateCreateHelp = 
let doc = "Create a Template from a file" in
let exits = Term.default_exits in
  Term.(const templateCreate $ nameArg $ pathArg), 
    Term.info "TemplateCreate" ~doc ~exits

let templateDetailsHelp = 
let doc = "Show Details about a Template" in
let exits = Term.default_exits in
  Term.(const templateDetails $ nameArg ), 
    Term.info "TemplateDetails" ~doc ~exits

let templateListHelp = 
let doc = "List all Templates for this user" in
let exits = Term.default_exits in
  Term.(const templateList $ const ()), 
    Term.info "TemplateList" ~doc ~exits

let deployStackHelp = 
let doc = "Deploy a Stack to a Provider" in
let exits = Term.default_exits in
  Term.(const deployStack $ deployArg $ templateArg $ providerArg ), 
    Term.info "DeployStack" ~doc ~exits 
 
let deployRemoveHelp = 
let doc = "Remove a deployed stack from a Provider" in
let exits = Term.default_exits in
  Term.(const deployRemove $ deployArg $ templateArg $ providerArg ), 
    Term.info "DeployRemove" ~doc ~exits 

(* Run *)

let actions = [templateCreateHelp; templateDetailsHelp; templateListHelp; deployStackHelp; deployRemoveHelp]
let () = Term.(exit @@ eval_choice oCommanderHelp actions)
```

**Comment by shanewilson** [comment]
According to #1 file/dir calls don't work. I had to get around this by changing all dir/file types to just string.

```
let pathArg = {
  let doc = "$(docv) to template file";
  Arg.(
    required
    & opt(some(string), None)
    & info(["p", "path"], ~docv="PATH", ~doc)
  );
};
```

should work - although it is less safe I guess because you give up the fs checks.

**Comment by DrYSG** [comment]
#1 suggests a shim of using Node.Fs.existsSync , ok other than not having a pure solution, what are the practical drawbacks going that route?
